export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_BY_SEARCH = "FETCH_MOVIES_BY_SEARCH";
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const FETCH_MOVIE_REVIEWS = "FETCH_MOVIE_REVIEWS";
export const CLEANING_MOVIE_STATE = "CLEANING_MOVIE_STATE";

